name: contact_app
description: "Flutter Contact App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc_test: ^9.1.7
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_slidable: ^3.1.1
  fpdart: ^1.1.0
  go_router: ^14.1.2
  logger: ^2.4.0
  mockito: ^5.4.4
  mocktail: ^1.0.3
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  melos: ^6.1.0
  objectbox_generator: ^4.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
